version: "2.15"

init flag!

service:
  - nginx
    init: true
  - wordpress_php-fpm
    init: true
  - mariadb
    init: true
  -> all restart in case of crash

volume:
  - WordPress database in one
      - 2 users, one of them admin
      - admin's username shouldn't contain admin or administrator
  - WordPress website files in other one
  -> both volumes should be in /home/<login>/data of host machine

network: connection between containers
  -> no host or --link or links