services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/
    networks:
      - all
    init: true
    restart: on-failure
#  wordpress:
#    container_name: wordpress
#    build: ./requirements/wordpress/
#    volumes:
#      - wordpress:/var/www/html/
#    networks:
#      - all
#    init: true
#    restart: on-failure
#  mariadb:
#    container_name: mariadb
#    build: ./requirements/mariadb/
#    ports:
#      - 3306:3306
#    volumes:
#      - database:/var/lib/mysql
#    networks:
#      - all
#    init: true
#    restart: on-failure

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

networks:
  all: