services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - '443:443'
    volumes:
      - ~/data/wordpress_files:/var/www/inception/
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress_files:/var/www/inception/ # PATH?
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - database:/var/lib/mysql # PATH?
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress_files

networks:
  all: