install and configure WordPress & php-fpm (only)
domain name shaas.42.fr -> should point to local IP adress


FROM Alpine or Debian (not latest!!!)
ENTRYPOINT musn’t be started with a command running an infinite
loop